# Generated by Django 4.2 on 2023-06-08 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=100)),
                ('client_email', models.CharField(max_length=100)),
                ('client_phone', models.CharField(max_length=100)),
                ('client_subject', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('client_message', models.TextField(blank=True, default='', null=True)),
                ('product_id', models.IntegerField(blank=True, default=0, null=True)),
                ('product_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('product_image', models.ImageField(blank=True, default='', null=True, upload_to='uploads')),
                ('product_price', models.IntegerField(blank=True, default=0, null=True)),
                ('product_web_link', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('product_technology', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Website_Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Website_Technology',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_image', models.ImageField(blank=True, default='', null=True, upload_to='uploads')),
                ('product_price', models.IntegerField()),
                ('product_web_link', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.website_category')),
                ('product_technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.website_technology')),
            ],
        ),
    ]
